name: oidc_client
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^2.4.1
  google_sign_in: ^5.3.0
  http: ^0.13.4
  sign_in_with_apple: ^3.3.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.0
  very_good_analysis: ^2.4.0
