name: keycloak_oidc_client
description: A Very Good Project created by Very Good CLI.
version: 0.0.1-dev.1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.4
  native_authorization:
    git:
      url: https://github.com/daniellampl/oidc_client.git
      ref: main
      path: packages/native_authorization/
  oidc_client:
    git:
      url: https://github.com/daniellampl/oidc_client.git
      ref: main
      path: packages/oidc_client/

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
