name: keycloak_oidc_client
description: A Flutter OIDC client on steroids optimized for Keycloak.
version: 0.0.1-dev.1
repository: https://github.com/daniellampl/oidc_client/tree/main/packages/keycloak_oidc_client

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.4
  oidc_client: ^0.0.1-dev.1

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
